### ISSUE TITLE
No module named 'utils.ex'

### ISSUE THREAD

**Issue by kkkparty** [DongHande/AutoDebias#2]
生成了so文件依然显示无法找到utils.ex 请大佬指点一下,谢谢!

**Comment by DongHande** [comment]
感谢您对我们工作的关注。
首先，根据我们仓库提供python和各种库的版本，是可以直接运行代码的，不需要自己生成so文件。
如果你想自己生成so文件，请自行查阅cppimport这个库相关的用法。主要关注下文件路径。

**Comment by bnu-wangxun** [comment]
How to solve "ModuleNotFoundError: No module named 'utils.ex'"? I also face this issue.

sloved.

**Comment by XTengineer** [comment]
> How to solve "ModuleNotFoundError: No module named 'utils.ex'"? I also face this issue.
> 
> sloved.

Hi, I also suffer from this issue. How did you solve this issue  "ModuleNotFoundError: No module named 'utils.ex'"

**Comment by DongXiang-CV** [comment]
> How to solve "ModuleNotFoundError: No module named 'utils.ex'"? I also face this issue.
> 
> sloved.

Hi. I also suffer from this issue. Can you tell me how did you solve this? Thank you very much!

**Comment by kkkparty** [comment]
&nbsp;You should first configure the environment as required




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DongHande/AutoDebias"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 凌晨4:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DongHande/AutoDebias] No module named 'utils.ex' (#2)





  
How to solve "ModuleNotFoundError: No module named 'utils.ex'"? I also face this issue.
 
sloved.
  
Hi, I also suffer from this issue. How did you solve this issue  "ModuleNotFoundError: No module named 'utils.ex'"
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XTengineer** [comment]
> &nbsp;You should first configure the environment as required
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "DongHande/AutoDebias" ***@***.***&gt;; 发送时间:&nbsp;2021年10月30日(星期六) 凌晨4:01 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [DongHande/AutoDebias] No module named 'utils.ex' (#2) How to solve "ModuleNotFoundError: No module named 'utils.ex'"? I also face this issue. sloved. Hi, I also suffer from this issue. How did you solve this issue "ModuleNotFoundError: No module named 'utils.ex'" — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.


Hi. Thank you. I think I have configure the environment as required. 

I download your code and directly run it. But it shows:
ModuleNotFoundError: No module named 'utils.ex'

If I delete import utils.ex as ex and add exp= cppimport.imp_from_filepath('utils/ex.cpp'), it still shows the following error:
#include <forward_list>
^~~~~~~~~~~~~~
1 error generated.
error: command 'gcc' failed with exit status 1

Can you help me how to run your code if possible. Thank you very much!

**Comment by DongXiang-CV** [comment]
> &nbsp;You should first configure the environment as required
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "DongHande/AutoDebias" ***@***.***&gt;; 发送时间:&nbsp;2021年10月30日(星期六) 凌晨4:01 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [DongHande/AutoDebias] No module named 'utils.ex' (#2) How to solve "ModuleNotFoundError: No module named 'utils.ex'"? I also face this issue. sloved. Hi, I also suffer from this issue. How did you solve this issue "ModuleNotFoundError: No module named 'utils.ex'" — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Hi, thank you. I think I have configured the environment as required

I download the code and directly run it. But it shows:
**ModuleNotFoundError: No module named 'utils.ex'**

If I delete `import utils.ex as ex` and add `exp= cppimport.imp_from_filepath('utils/ex.cpp')`, it still shows the following error:
**#include <forward_list>
         ^~~~~~~~~~~~~~
1 error generated.
error: command 'gcc' failed with exit status 1**

Can you help me how to run the code if possible. Thank you very much!

**Comment by kkkparty** [comment]
You should pay attention to the version of python，I had the same problem before, configuring the virtual environment with anaconda and reinstalling all the packages, and try it again
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DongHande/AutoDebias"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 上午9:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DongHande/AutoDebias] No module named 'utils.ex' (#2)





  
&nbsp;You should first configure the environment as required
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "DongHande/AutoDebias" @.&gt;; 发送时间:&nbsp;2021年10月30日(星期六) 凌晨4:01 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [DongHande/AutoDebias] No module named 'utils.ex' (#2) How to solve "ModuleNotFoundError: No module named 'utils.ex'"? I also face this issue. sloved. Hi, I also suffer from this issue. How did you solve this issue "ModuleNotFoundError: No module named 'utils.ex'" — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
Hi. Thank you. I think I have configure the environment as required.
 
I download your code and directly run it. But it shows:
 ModuleNotFoundError: No module named 'utils.ex'
 
If I delete import utils.ex as ex and add exp= cppimport.imp_from_filepath('utils/ex.cpp'), it still shows the following error:
 #include <forward_list&gt;
 ^~~~~~~~~~~~~~
 1 error generated.
 error: command 'gcc' failed with exit status 1
 
Can you help me how to run your code if possible. Thank you very much!
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DongXiang-CV** [comment]
> You should pay attention to the version of python，I had the same problem before, configuring the virtual environment with anaconda and reinstalling all the packages, and try it again ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "DongHande/AutoDebias" ***@***.***&gt;; 发送时间:&nbsp;2021年10月30日(星期六) 上午9:45 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [DongHande/AutoDebias] No module named 'utils.ex' (#2) &nbsp;You should first configure the environment as required … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "DongHande/AutoDebias" @.&gt;; 发送时间:&nbsp;2021年10月30日(星期六) 凌晨4:01 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [DongHande/AutoDebias] No module named 'utils.ex' (#2) How to solve "ModuleNotFoundError: No module named 'utils.ex'"? I also face this issue. sloved. Hi, I also suffer from this issue. How did you solve this issue "ModuleNotFoundError: No module named 'utils.ex'" — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. Hi. Thank you. I think I have configure the environment as required. I download your code and directly run it. But it shows: ModuleNotFoundError: No module named 'utils.ex' If I delete import utils.ex as ex and add exp= cppimport.imp_from_filepath('utils/ex.cpp'), it still shows the following error: #include <forward_list&gt; ^~~~~~~~~~~~~~ 1 error generated. error: command 'gcc' failed with exit status 1 Can you help me how to run your code if possible. Thank you very much! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Thank you for your reply. So after you re-installl all the packages then the "ModuleNotFoundError: No module named 'utils.ex'" automatically disappears, right? you never modify the authors' code?

**Comment by kkkparty** [comment]
yeah ,just have a try ,then you will make it




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DongHande/AutoDebias"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月30日(星期六) 上午10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DongHande/AutoDebias] No module named 'utils.ex' (#2)





  
You should pay attention to the version of python，I had the same problem before, configuring the virtual environment with anaconda and reinstalling all the packages, and try it again ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "DongHande/AutoDebias" @.&gt;; 发送时间:&nbsp;2021年10月30日(星期六) 上午9:45 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [DongHande/AutoDebias] No module named 'utils.ex' (#2) &nbsp;You should first configure the environment as required … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "DongHande/AutoDebias" @.&gt;; 发送时间:&nbsp;2021年10月30日(星期六) 凌晨4:01 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [DongHande/AutoDebias] No module named 'utils.ex' (#2) How to solve "ModuleNotFoundError: No module named 'utils.ex'"? I also face this issue. sloved. Hi, I also suffer from this issue. How did you solve this issue "ModuleNotFoundError: No module named 'utils.ex'" — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. Hi. Thank you. I think I have configure the environment as required. I download your code and directly run it. But it shows: ModuleNotFoundError: No module named 'utils.ex' If I delete import utils.ex as ex and add exp= cppimport.imp_from_filepath('utils/ex.cpp'), it still shows the following error: #include <forward_list&gt; ^~~~~~~~~~~~~~ 1 error generated. error: command 'gcc' failed with exit status 1 Can you help me how to run your code if possible. Thank you very much! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
Thank you for your reply. So after you re-installl all the packages then the "ModuleNotFoundError: No module named 'utils.ex'" automatically disappears, right? you never modify the authors' code?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
